import { translate } from "googletrans";

export const languages = [
  { name: "Abkhaz", code: "ab", popularity: 5 },
  { name: "Acehnese", code: "ace", popularity: 5 },
  { name: "Acholi", code: "ach", popularity: 5 },
  { name: "Afar", code: "aa", popularity: 5 },
  { name: "Afrikaans", code: "af", popularity: 20 },
  { name: "Albanian", code: "sq", popularity: 15 },
  { name: "Alur", code: "alz", popularity: 5 },
  { name: "Amharic", code: "am", popularity: 15 },
  { name: "Arabic", code: "ar", popularity: 80 },
  { name: "Armenian", code: "hy", popularity: 10 },
  { name: "Assamese", code: "as", popularity: 10 },
  { name: "Avar", code: "av", popularity: 5 },
  { name: "Awadhi", code: "awa", popularity: 5 },
  { name: "Aymara", code: "ay", popularity: 5 },
  { name: "Azerbaijani", code: "az", popularity: 15 },
  { name: "Balinese", code: "ban", popularity: 5 },
  { name: "Baluchi", code: "bal", popularity: 5 },
  { name: "Bambara", code: "bm", popularity: 5 },
  { name: "Baoulé", code: "bci", popularity: 5 },
  { name: "Bashkir", code: "ba", popularity: 5 },
  { name: "Basque", code: "eu", popularity: 10 },
  { name: "Batak Karo", code: "btx", popularity: 5 },
  { name: "Batak Simalungun", code: "bts", popularity: 5 },
  { name: "Batak Toba", code: "bbc", popularity: 5 },
  { name: "Belarusian", code: "be", popularity: 10 },
  { name: "Bemba", code: "bem", popularity: 5 },
  { name: "Bengali", code: "bn", popularity: 70 },
  { name: "Betawi", code: "bew", popularity: 5 },
  { name: "Bhojpuri", code: "bho", popularity: 15 },
  { name: "Bikol", code: "bik", popularity: 5 },
  { name: "Bosnian", code: "bs", popularity: 10 },
  { name: "Breton", code: "br", popularity: 5 },
  { name: "Bulgarian", code: "bg", popularity: 15 },
  { name: "Buryat", code: "bxr", popularity: 5 },
  { name: "Cantonese", code: "yue", popularity: 30 },
  { name: "Catalan", code: "ca", popularity: 15 },
  { name: "Cebuano", code: "ceb", popularity: 10 },
  { name: "Chamorro", code: "ch", popularity: 5 },
  { name: "Chechen", code: "ce", popularity: 5 },
  { name: "Chichewa", code: "ny", popularity: 5 },
  { name: "Chinese (Simplified)", code: "zh-CN", popularity: 100 },
  { name: "Chinese (Traditional)", code: "zh-TW", popularity: 50 },
  { name: "Chuukese", code: "chk", popularity: 5 },
  { name: "Chuvash", code: "cv", popularity: 5 },
  { name: "Corsican", code: "co", popularity: 5 },
  { name: "Crimean Tatar", code: "crh", popularity: 5 },
  { name: "Croatian", code: "hr", popularity: 15 },
  { name: "Czech", code: "cs", popularity: 15 },
  { name: "Danish", code: "da", popularity: 15 },
  { name: "Dari", code: "prs", popularity: 10 },
  { name: "Dhivehi", code: "dv", popularity: 5 },
  { name: "Dinka", code: "din", popularity: 5 },
  { name: "Dogri", code: "doi", popularity: 5 },
  { name: "Dombe", code: "dov", popularity: 5 },
  { name: "Dutch", code: "nl", popularity: 25 },
  { name: "Dyula", code: "dyu", popularity: 5 },
  { name: "Dzongkha", code: "dz", popularity: 5 },
  { name: "English", code: "en", popularity: 100 },
  { name: "Esperanto", code: "eo", popularity: 10 },
  { name: "Estonian", code: "et", popularity: 10 },
  { name: "Ewe", code: "ee", popularity: 5 },
  { name: "Faroese", code: "fo", popularity: 5 },
  { name: "Fijian", code: "fj", popularity: 5 },
  { name: "Filipino", code: "fil", popularity: 20 },
  { name: "Finnish", code: "fi", popularity: 15 },
  { name: "Fon", code: "fon", popularity: 5 },
  { name: "French", code: "fr", popularity: 60 },
  { name: "Frisian", code: "fy", popularity: 5 },
  { name: "Friulian", code: "fur", popularity: 5 },
  { name: "Fulani", code: "ff", popularity: 5 },
  { name: "Ga", code: "gaa", popularity: 5 },
  { name: "Galician", code: "gl", popularity: 10 },
  { name: "Georgian", code: "ka", popularity: 10 },
  { name: "German", code: "de", popularity: 50 },
  { name: "Greek", code: "el", popularity: 20 },
  { name: "Guarani", code: "gn", popularity: 5 },
  { name: "Gujarati", code: "gu", popularity: 15 },
  { name: "Haitian Creole", code: "ht", popularity: 10 },
  { name: "Hakha Chin", code: "cnh", popularity: 5 },
  { name: "Hausa", code: "ha", popularity: 10 },
  { name: "Hawaiian", code: "haw", popularity: 5 },
  { name: "Hebrew", code: "he", popularity: 15 },
  { name: "Hiligaynon", code: "hil", popularity: 5 },
  { name: "Hindi", code: "hi", popularity: 80 },
  { name: "Hmong", code: "hmn", popularity: 5 },
  { name: "Hungarian", code: "hu", popularity: 15 },
  { name: "Hunsrik", code: "hrx", popularity: 5 },
  { name: "Iban", code: "iba", popularity: 5 },
  { name: "Icelandic", code: "is", popularity: 10 },
  { name: "Igbo", code: "ig", popularity: 10 },
  { name: "Ilocano", code: "ilo", popularity: 5 },
  { name: "Indonesian", code: "id", popularity: 30 },
  { name: "Irish", code: "ga", popularity: 10 },
  { name: "Italian", code: "it", popularity: 40 },
  { name: "Jamaican Patois", code: "jam", popularity: 5 },
  { name: "Japanese", code: "ja", popularity: 50 },
  { name: "Javanese", code: "jv", popularity: 20 },
  { name: "Jingpo", code: "kac", popularity: 5 },
  { name: "Kalaallisut", code: "kl", popularity: 5 },
  { name: "Kannada", code: "kn", popularity: 15 },
  { name: "Kanuri", code: "kr", popularity: 5 },
  { name: "Kapampangan", code: "pam", popularity: 5 },
  { name: "Kazakh", code: "kk", popularity: 15 },
  { name: "Khasi", code: "kha", popularity: 5 },
  { name: "Khmer", code: "km", popularity: 10 },
  { name: "Kiga", code: "cgg", popularity: 5 },
  { name: "Kikongo", code: "kg", popularity: 5 },
  { name: "Kinyarwanda", code: "rw", popularity: 10 },
  { name: "Kituba", code: "ktu", popularity: 5 },
  { name: "Kokborok", code: "trp", popularity: 5 },
  { name: "Komi", code: "kv", popularity: 5 },
  { name: "Konkani", code: "kok", popularity: 5 },
  { name: "Korean", code: "ko", popularity: 40 },
  { name: "Krio", code: "kri", popularity: 5 },
  { name: "Kurdish (Kurmanji)", code: "ku", popularity: 10 },
  { name: "Kurdish (Sorani)", code: "ckb", popularity: 5 },
  { name: "Kyrgyz", code: "ky", popularity: 10 },
  { name: "Lao", code: "lo", popularity: 5 },
  { name: "Latgalian", code: "ltg", popularity: 5 },
  { name: "Latin", code: "la", popularity: 10 },
  { name: "Latvian", code: "lv", popularity: 10 },
  { name: "Ligurian", code: "lij", popularity: 5 },
  { name: "Limburgish", code: "li", popularity: 5 },
  { name: "Lingala", code: "ln", popularity: 10 },
  { name: "Lithuanian", code: "lt", popularity: 10 },
  { name: "Lombard", code: "lmo", popularity: 5 },
  { name: "Luganda", code: "lg", popularity: 5 },
  { name: "Luo", code: "luo", popularity: 5 },
  { name: "Luxembourgish", code: "lb", popularity: 5 },
  { name: "Macedonian", code: "mk", popularity: 10 },
  { name: "Madurese", code: "mad", popularity: 5 },
  { name: "Maithili", code: "mai", popularity: 10 },
  { name: "Makassar", code: "mak", popularity: 5 },
  { name: "Malagasy", code: "mg", popularity: 5 },
  { name: "Malay", code: "ms", popularity: 30 },
  { name: "Malay (Jawi)", code: "ms-Arab", popularity: 5 },
  { name: "Malayalam", code: "ml", popularity: 15 },
  { name: "Maltese", code: "mt", popularity: 5 },
  { name: "Mam", code: "mam", popularity: 5 },
  { name: "Manx", code: "gv", popularity: 5 },
  { name: "Maori", code: "mi", popularity: 5 },
  { name: "Marathi", code: "mr", popularity: 15 },
  { name: "Marshallese", code: "mh", popularity: 5 },
  { name: "Marwadi", code: "mwr", popularity: 5 },
  { name: "Mauritian Creole", code: "mfe", popularity: 5 },
  { name: "Meadow Mari", code: "mhr", popularity: 5 },
  { name: "Meiteilon (Manipuri)", code: "mni", popularity: 5 },
  { name: "Minang", code: "min", popularity: 5 },
  { name: "Mizo", code: "lus", popularity: 5 },
  { name: "Mongolian", code: "mn", popularity: 10 },
  { name: "Myanmar (Burmese)", code: "my", popularity: 10 },
  { name: "Nahuatl (Eastern Huasteca)", code: "nhe", popularity: 5 },
  { name: "Ndau", code: "ndc", popularity: 5 },
  { name: "Ndebele (South)", code: "nr", popularity: 5 },
  { name: "Nepalbhasa (Newari)", code: "new", popularity: 5 },
  { name: "Nepali", code: "ne", popularity: 10 },
  { name: "NKo", code: "nqo", popularity: 5 },
  { name: "Norwegian (Bokmål)", code: "nb", popularity: 15 },
  { name: "Nuer", code: "nus", popularity: 5 },
  { name: "Occitan", code: "oc", popularity: 5 },
  { name: "Odia (Oriya)", code: "or", popularity: 10 },
  { name: "Oromo", code: "om", popularity: 5 },
  { name: "Ossetian", code: "os", popularity: 5 },
  { name: "Pangasinan", code: "pag", popularity: 5 },
  { name: "Papiamento", code: "pap", popularity: 5 },
  { name: "Pashto", code: "ps", popularity: 10 },
  { name: "Persian", code: "fa", popularity: 25 },
  { name: "Polish", code: "pl", popularity: 20 },
  { name: "Portuguese (Brazil)", code: "pt-BR", popularity: 40 },
  { name: "Portuguese (Portugal)", code: "pt-PT", popularity: 40 },
  { name: "Punjabi (Gurmukhi)", code: "pa", popularity: 20 },
  { name: "Punjabi (Shahmukhi)", code: "pa-Arab", popularity: 5 },
  { name: "Quechua", code: "qu", popularity: 5 },
  { name: "Qʼeqchiʼ", code: "kek", popularity: 5 },
  { name: "Romani", code: "rom", popularity: 5 },
  { name: "Romanian", code: "ro", popularity: 15 },
  { name: "Rundi", code: "rn", popularity: 5 },
  { name: "Russian", code: "ru", popularity: 60 },
  { name: "Sami (North)", code: "se", popularity: 5 },
  { name: "Samoan", code: "sm", popularity: 5 },
  { name: "Sango", code: "sg", popularity: 5 },
  { name: "Sanskrit", code: "sa", popularity: 5 },
  { name: "Santali", code: "sat", popularity: 5 },
  { name: "Scots Gaelic", code: "gd", popularity: 5 },
  { name: "Sepedi", code: "nso", popularity: 5 },
  { name: "Serbian", code: "sr", popularity: 15 },
  { name: "Sesotho", code: "st", popularity: 5 },
  { name: "Seychellois Creole", code: "crs", popularity: 5 },
  { name: "Shan", code: "shn", popularity: 5 },
  { name: "Shona", code: "sn", popularity: 5 },
  { name: "Sicilian", code: "scn", popularity: 5 },
  { name: "Silesian", code: "szl", popularity: 5 },
  { name: "Sindhi", code: "sd", popularity: 10 },
  { name: "Sinhala", code: "si", popularity: 10 },
  { name: "Slovak", code: "sk", popularity: 10 },
  { name: "Slovenian", code: "sl", popularity: 10 },
  { name: "Somali", code: "so", popularity: 10 },
  { name: "Spanish", code: "es", popularity: 90 },
  { name: "Sundanese", code: "su", popularity: 10 },
  { name: "Susu", code: "sus", popularity: 5 },
  { name: "Swahili", code: "sw", popularity: 20 },
  { name: "Swati", code: "ss", popularity: 5 },
  { name: "Swedish", code: "sv", popularity: 15 },
  { name: "Tahitian", code: "ty", popularity: 5 },
  { name: "Tajik", code: "tg", popularity: 10 },
  { name: "Tamazight", code: "zgh", popularity: 5 },
  { name: "Tamazight (Tifinagh)", code: "tzm", popularity: 5 },
  { name: "Tamil", code: "ta", popularity: 20 },
  { name: "Tatar", code: "tt", popularity: 5 },
  { name: "Telugu", code: "te", popularity: 15 },
  { name: "Tetum", code: "tet", popularity: 5 },
  { name: "Thai", code: "th", popularity: 20 },
  { name: "Tibetan", code: "bo", popularity: 5 },
  { name: "Tigrinya", code: "ti", popularity: 5 },
  { name: "Tiv", code: "tiv", popularity: 5 },
  { name: "Tok Pisin", code: "tpi", popularity: 5 },
  { name: "Tongan", code: "to", popularity: 5 },
  { name: "Tsonga", code: "ts", popularity: 5 },
  { name: "Tswana", code: "tn", popularity: 5 },
  { name: "Tulu", code: "tcy", popularity: 5 },
  { name: "Tumbuka", code: "tum", popularity: 5 },
  { name: "Turkish", code: "tr", popularity: 30 },
  { name: "Turkmen", code: "tk", popularity: 5 },
  { name: "Tuvan", code: "tyv", popularity: 5 },
  { name: "Twi", code: "tw", popularity: 5 },
  { name: "Udmurt", code: "udm", popularity: 5 },
  { name: "Ukrainian", code: "uk", popularity: 30 },
  { name: "Urdu", code: "ur", popularity: 25 },
  { name: "Uyghur", code: "ug", popularity: 5 },
  { name: "Uzbek", code: "uz", popularity: 15 },
  { name: "Venda", code: "ve", popularity: 5 },
  { name: "Venetian", code: "vec", popularity: 5 },
  { name: "Vietnamese", code: "vi", popularity: 30 },
  { name: "Waray", code: "war", popularity: 5 },
  { name: "Welsh", code: "cy", popularity: 10 },
  { name: "Wolof", code: "wo", popularity: 5 },
  { name: "Xhosa", code: "xh", popularity: 5 },
  { name: "Yakut", code: "sah", popularity: 5 },
  { name: "Yiddish", code: "yi", popularity: 5 },
  { name: "Yoruba", code: "yo", popularity: 10 },
  { name: "Yucatec Maya", code: "yua", popularity: 5 },
  { name: "Zapotec", code: "zap", popularity: 5 },
  { name: "Zulu", code: "zu", popularity: 10 }
] as const;


export type LanguageCode = typeof languages[number]["code"];
export type LanguageName = typeof languages[number]["name"];
export type Language = { name: LanguageName; code: LanguageCode; popularity: number };
export type Translation = Awaited<ReturnType<typeof translate>>;
export type Translate = (text: string | string[], options: { to: LanguageCode; from?: LanguageCode }) => Promise<Translation>;

export async function tl(text: string | string[], from: LanguageCode | undefined, to: LanguageCode): Promise<Translation> {
  return translate(text, { to, from });
}

export const languagesSorted = [...languages].sort((a, b) => a.popularity - b.popularity);